### PR TITLE
Update proj to 7.2.0

### PR DESCRIPTION
**Pull request by urschrei**

### CODE REVIEW

**Comment by michaelkirk** [comment]
LGTM - I don't really remember if/how all the "autobuild" stuff works for dockerhub. 

IIRC last time I made changes to the containers I locally built and manually published the images. You're welcome to do whatever works. LMK if you have issues - happy to help debug.

**Comment by urschrei** [comment]
I should be able to build this locally, right? Both the existing and updated Dockerfile fail to build local images for me, with a fairly cryptic `g++: fatal error: Killed signal terminated program cc1plus`, so I can't push a new version…

**Comment by michaelkirk** [comment]
Yep, should work. Can you provide the full output transcript?

**Comment by urschrei** [comment]
running `docker build -f libproj-builder.Dockerfile .`

https://gist.github.com/urschrei/1f063d9d6f38073ca743766096d6c6fb

**Comment by urschrei** [comment]
(vague possibility that it's a memory issue at my end and actually nothing to worry about)

**Review by frewsxcv — APPROVED** [review]

**Comment by michaelkirk** [comment]
> (vague possibility that it's a memory issue at my end and actually nothing to worry about)

In case you haven't already, could you try upping the memory allocated to your docker container, and if that doesn't work, maybe removing the "-j" option so that you have only one instance going?

**Pull request merged**
