### PR TITLE
Add instructions for updating proj docker images and repos

### PR DESCRIPTION
**Pull request by urschrei**

### CODE REVIEW

**Comment by urschrei** [comment]
Thinking a bit more about this, it seems clear that the next step here should be pushing a tag to run steps 2 to 9 using GH actions.

**Comment by michaelkirk** [comment]
Thanks for documenting! It is a pretty arduous process right now, isn't it? 😞

There are several moving parts, so I haven't really felt confident that I knew how to automate more of this in a robust way.  I'd be a little nervous about any system which involves automatically pushing commits to our other repos master branches.

One place to start could be scripting more of the container building and tagging so that it can be run more efficiently even if manually. We'd need to script that stuff anyway if we want it in CI one day.

**Review by michaelkirk — APPROVED** [review]
docs look good!

**Comment by urschrei** [comment]
> I'd be a little nervous about any system which involves automatically pushing commits to our other repos master branches.

Oh yeah we don't want that, hence only having the docker build and push steps (2-9) automated via GH actions.

**Comment by michaelkirk** [comment]
ah, push **to docker hub**, I'm much less concerned about that. 👍 

Not sure if you're already aware, but there is some machinery **in** docker hub for doing automatic builds. Though last time I tried it, I couldn't figure out how to convey the container dependency build order; Specifically, that the projbuilder container needs to happen *first* and then the other images need to be based on **that** latest build of projbuilder. 

It might be doable, but I am not very patient. It might be better to instead script it explicitly and put it into a GH action.

**Comment by urschrei** [comment]
Well today was my first ever interaction with Docker Hub (and builds generally), and from the quick read I had the GH actions route seems preferable. But yeah, figuring out if we can get the order to work may be tricky.

**Pull request merged**
